#ifndef CONSTANTS_FXH

#define CONSTANTS_FXH

#define POINT_MAX_LIGHTS_PER_OBJECT 10
#define MINIMUM_LENGTH_VALUE 0.00000000001f
#define ATTENUATION_MULTIPLIER 8
#define SKINNED_EFFECT_MAX_BONES 72
#define WEIGHTS_PER_VERTEX 4
#define SHADOW_BIAS 0.0055f
#define SHADOW_DEPTH_BIAS 0.0001f
#define SHADOW_POINT_MAX_DIST 50.0f

#endif